### ISSUE TITLE
Consider binary cache?

### ISSUE THREAD

**Issue by SuperKenVery** [s0LA1337/ctf-nix-shell#1]
Thanks a lot for your great work! But it seems that it still takes some time for me to build the environment (~20mins) :(

Would you please consider providing a binary cache at, for example, cachix? That would be great!

There are ready-made GitHub Actions that generate the caches on each push, so it shouldn't be of too much a trouble.

**Comment by SoraTenshi** [comment]
Ok first of all: i haven't touched this in quite a while, and i am literally surprised anyone uses it.
2nd: I would have to investigate it, if you're knowledgeable in this regard, i am more than hobby to review a PR.

**Comment by SuperKenVery** [comment]
> i am literally surprised anyone uses it.

I came here by searching `ctf nix shell` on google, congratulations!

> i am more than hobby to review a PR.

Okay I'm working on that :D
